require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Security/MarshalLoad:
  Enabled: false

Style/BeginBlock:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OptionalBooleanParameter:
  AllowedMethods: ['initialize']

Style/SymbolArray:
  EnforcedStyle: brackets

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
